resolver: nightly-2023-10-22

packages:
- .

allow-newer: true

flags:
#  hid-examples:
#    with-pg: True

extra-deps:
  - Chart-1.9.5
  - Chart-diagrams-1.9.5.1
  - streaming-utils-0.2.5.0
  - HDBC-postgresql-2.4.0.0